### ISSUE TITLE
flake8 config not working on 1.5.1

### ISSUE THREAD

**Issue by staticdev** [terrencepreilly/darglint#110]
I tried the following:

I have a .darglint:

```ini
[darglint]
strictness = short
```

I deleted it and put this content in the end of .flake8. When I run it, it is not considering this strictness.

From the code code on this repo I also found this to add on pyproject.toml:

```toml
[tool.poetry.plugins."flake8.extension"]
"DAR" = "darglint.flake8_entry:DarglintChecker"
```

But it also did not solve the problem. There is no mention on how to configure it on flake8 section of this package. Just on the changelog and release notes.
